### ISSUE TITLE
Оновлення стейту

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [MedmakNP/test123#4]
В функція `handleDelete` `handleAdd` і можливо в інших
Якщо нове значення стейту залежить від мнулого значення - потрібно використовувати функцію для оновлення 
https://reactjs.org/docs/state-and-lifecycle.html#state-updates-may-be-asynchronous

**Comment by MedmakNP** [comment]
Добрий вечір, я використав функцію для оновлення, але не знаю чи правильно це

**Comment by DmitriiMelnikOnix** [comment]
Було так
```
 handleDelete = (index) => {
    const { tableDataArr } = this.state;
    const newDeleteArr = [...tableDataArr];
    newDeleteArr.splice(index, 1);
    this.setState({ tableDataArr: newDeleteArr }, this.updateTable);
  };
```
А краще так
```
 handleDelete = (index) => {
    this.setState(({tableDataArr}) => {
       const newDeleteArr = [...tableDataArr];
       newDeleteArr.splice(index, 1);
       return { tableDataArr: newDeleteArr };
    })
  };
```
А `this.updateTable` тут не використовується 

Справа в тому що якщо setState буде викликаний декілька разів за дуже короктий час, то він може відпрацювати не завсім коректно в твоєму варіанті

Простий приклад

```
const { count } = this.state;
this.setState({count: count + 1})
this.setState({count: count + 1})
```

В цьому випадку через замикання в обох в обох setState буде однакове значення count і він збільшиться не на 2, а на 1

А ось другий приклад

```
this.setState((count) => ({count: count + 1}))
this.setState((count) => ({count: count + 1}))
this.setState((count) => ({count: count + 1}))
this.setState((count) => ({count: count + 1}))
```
Тут замикання немає, а отже в цю функцію кожного разу потрапляє нове значення стейту і за ці 4 рядки count збульшиться на 4
